package main;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * This class is used to ask the player questions and assign the answers
 */
public class PlayerChoices {
    private String question;
    private List<String> equipmentOptions;

    private boolean isItem = true;

    private final Map<String, List<PlayerChoices>> followQs = new HashMap<>();

    /**
     * This accepts the question and the List of equipment and assigns the equipment based on the
     * response to the question
     * @param question The question being asked on what to put in the starter bag
     * @param equipmentOptions The List generated by answering questions
     */
    public PlayerChoices(String question, List<String> equipmentOptions) {
        this.question = question;
        this.equipmentOptions = equipmentOptions;
    }

    /**
     * {@inheritDoc}
     * @param isItem Checks whether the item should go in the inventory or not
     */
    public PlayerChoices(String question, List<String> equipmentOptions, boolean isItem) {
        this.question = question;
        this.equipmentOptions = equipmentOptions;
        this.isItem = isItem;
    }

    /**
     * This asks the follow-up questions to the player
     * @param answer The answer to the previous question
     * @param followQuestions The follow-up question to ask dependent on a specific answer
     */
    public void fQuestion(String answer, PlayerChoices followQuestions) {
        followQs.putIfAbsent(answer, new ArrayList<>());
        followQs.get(answer).add(followQuestions);
    }

    /**
     * Gets the question being asked and returns it
     * @return The question being asked
     */
    public String getQuestion() {
        return question;
    }

    /**
     * Gets the list of equipment options and returns it
     * @return The list of equipment options
     */
    public List<String> getEquipmentOptions() {
        return equipmentOptions;
    }

    /**
     * Boolean checks if the object being added into the List of Equipment Options is actually an item
     * @return true if item, false if not
     */
    public boolean isItem() {
        return isItem;
    }

    /**
     * Used in branching path questions, this gets the follow-up questions and returns them
     * @return the follow up question
     */
    public Map<String, List<PlayerChoices>> getFollowQs() {
        return followQs;
    }
}
